// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/personas/Header.vue')['default']
    MenuItem: typeof import('./src/components/commons/MenuItem.vue')['default']
    PersonaHeader: typeof import('./src/components/personas/PersonaHeader.vue')['default']
    PersonaList: typeof import('./src/components/personas/PersonaList.vue')['default']
    PersonaMenu: typeof import('./src/components/personas/PersonaMenu.vue')['default']
    PersonaTable: typeof import('./src/components/personas/PersonaTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
  }
}
